name = "Gemini"
uuid = "0e52221f-e550-4e6d-bdf1-4c59b98d8cd5"
authors = ["Rory Linehan <rorylinehan@protonmail.ch>"]
version = "0.2.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"

[compat]
julia = "1"
JSON = "0.21.2"
WebSockets = "1"

[targets]
test = ["Test"]
